package simpledb.execution;

import simpledb.common.Utility;
import simpledb.transaction.TransactionAbortedException;
import simpledb.common.DbException;
import simpledb.storage.Tuple;
import simpledb.storage.TupleDesc;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    private JoinPredicate joinPredicate;

    OpIterator[] childrens = new OpIterator[2];

    private Tuple tuple;
    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        this.joinPredicate = p;
        this.childrens[0] = child1;
        this.childrens[1] = child2;
    }

    public JoinPredicate getJoinPredicate() {
        return this.joinPredicate;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        return this.childrens[0].getTupleDesc().
                getFieldName(joinPredicate.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        return this.childrens[1].getTupleDesc().
                getFieldName(joinPredicate.getField2());
    }

    /**
     * @see TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        return TupleDesc.merge(this.childrens[0].getTupleDesc(),
                this.childrens[1].getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        super.open();
        childrens[0].open();
        childrens[1].open();
        if (childrens[0].hasNext()) {
            tuple = childrens[0].next();
        }
    }

    public void close() {
        super.close();
        childrens[0].close();
        childrens[1].close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        open();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        if (tuple == null) return null;
        while (true) {
            if (childrens[1].hasNext()) {
                Tuple tuple2 = childrens[1].next();
                if (this.joinPredicate.filter(tuple, tuple2)) {
                    Tuple res = new Tuple(getTupleDesc());
                    for (int i = 0; i < (tuple.getTupleDesc().numFields() +
                            tuple2.getTupleDesc().numFields()); i ++ ) {
                        if (i < tuple.getTupleDesc().numFields()) {
                            res.setField(i, tuple.getField(i));
                        } else {
                            res.setField(i, tuple2.getField(i -
                                    tuple.getTupleDesc().numFields()));
                        }
                    }
                    return res;
                }
            } else if (childrens[0].hasNext()) {
                tuple = childrens[0].next();
                childrens[1].rewind();
            } else {
                break;
            }
        }
        return null;
    }

    @Override
    public OpIterator[] getChildren() {
        return this.childrens;
    }

    @Override
    public void setChildren(OpIterator[] children) {
        this.childrens[0] = children[0];
        this.childrens[1] = children[1];
    }

}
